### ISSUE TITLE
Unowned fragments used in builds after disabled

### ISSUE THREAD

**Issue by Runebyte** [tpetrychyn/osrs-fragment-calc#3]
Disabling a fragment will no longer filter it from being used in builds.
Steps to reproduce: Select set effects Endless Knowledge and Last Recall (with tier 6), disable any fragment. Result: disabled fragments are not filtered like they previously were.

**Comment by anmart** [comment]
I think that's being fixed in #2, if I'm reading correctly. I had a similar issue with chain magic and un-owning zamorakian sight.

**Comment by tpetrychyn** [comment]
Fixed in #2
