### ISSUE TITLE
Sort fragments by internal ID order

### ISSUE THREAD

**Issue by anmart** [tpetrychyn/osrs-fragment-calc#4]
Finding fragments in runescape's fragment UI is a bit of a mess, but having them display in the internal ID order would allow you to search for specific ones a bit easier. the ID is already stored in the Fragment class, so no additional data is necessary.

**Comment by Ryan-Gole** [comment]
https://github.com/tpetrychyn/osrs-fragment-calc/pull/6

Made a PR to fix this. I was thinking of doing this before, but seeing the issue gave me the extra motivation.

**Comment by tpetrychyn** [comment]
Thanks Caos!
